[toolchain]
channel = "nightly-2023-12-20"
components = [ "rust-src", "rustfmt", "llvm-tools" ]
targets = [
# "thumbv7em-none-eabi",       # Cortex-M4 and Cortex-M7 (no FPU)
# "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+
"thumbv7m-none-eabi"        # Cortex-M3
# "thumbv7em-none-eabihf",     # Cortex-M4F and Cortex-M7F (with FPU)
# "thumbv8m.base-none-eabi"   # Cortex-M23
# "thumbv8m.main-none-eabi"   # Cortex-M33 (no FPU)
# "thumbv8m.main-none-eabihf" # Cortex-M33 (with FPU)
]
